### ISSUE TITLE
Nombres de script y funciones

### ISSUE THREAD

**Issue by daniprec** [PBM101/Manejo_Datos_Confidenciales#15]
Si queréis tener un código pythónico, os recomiendo respetar los convenios de nomenclatura:
- Nombres de script, todo en minúscula y usando barras bajas como espacios. Por ejemplo, `Manejo_de_datos.py` debería ser `manejo_de_datos.py` (o `manejo_datos.py` por simplificar).
- Nombres de funciones, todo en minúscula y usando barras bajas como espacios. Esto es especialmente importante, ya que en `Menu.py` usáis CamelCase, que es como se llaman a las clases. Una persona que sepa Python y lea la llamada a `LecturaManual` se pensará que es una clase, no una función.

**Comment by nico-olabarria** [comment]
Los nombres de las variables y archivos han sido cambiados para hacerlos más pythónicos.
